### PR TITLE
User interface - Milestone - II

### PR DESCRIPTION
**Pull request by SamArsanios**
In this project we:

1. created a new branch `user_interface.`
2. created the basic flow of the game.

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @SamArsanios and @necmigunduz. Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Linter is not passing all check, please review and fix the linter observations.
- [ ] The user_interface milestone is tricky it sometimes appear for the developer as it is actually building the logic of the game, when in reality is only setting the steps. This milestone doesn't expect a working application. This is more about laying out the steps the application will follow while the users play the game, meaning with this that we may have calls to methods that for the moment we may not even know how they will work. Also this steps should follow the next rules or constraints: (NOTE: I will mark the ones that the project already has, so you'll just have to work on the ones missing)
  - [x]  game asks players for their names
  - [x] game tells which player turn it is (without computing who the winner is)
  - [x] game asks the player to select from available moves
  - [x] game informs player if the selected move is invalid (without computing what an invalid move is)
  - [x]  game displays board after the player move (without computing which spots on the board are taken)
  - [x]  game informs player if the selected move is a winning move (without computing the winning move)
  - [x]  game informs player if the selected move is a draw move (without computing draw)
  - [x]  game repeats all actions for the next player's move
  
The uncheck ones are the ones missing from the project. There are some that are mention but not fully or correct implanted.

The loop is correct and should contain most of the things inside. It should check for a `winner`, or a `draw`, while this is in a way in the code it actually doesn't check the validity. Example: 
```ruby
# this says something about a winner but is not actually checking for one, 
# is just saying that if the gameover is equal to true it should assign a winner.
break if gameover = true
  winner = "#{player1 or player2}"
end

# An improved version could be something like this. 
if winner?
  game_over = true
end

break if game_over
```

- [x] When naming files and variables or arguments remember to separate more than one word names with an `_` underscore.

- [x] As I commented before this milestone is not about the logic or working methods, but only to show intent. Example:
```ruby
puts "#{current_player} your turn"
puts "please choose from these available options"
puts "1 - 9"
user_pick = gets.to_i

# ... some more code

if winner?
  puts "#{current_player} you have won! Congrats!"
end

if draw?
  puts "Nobody wins"
end
```
  As you can see we don't have the actual logic for the methods we are calling but we are just showing the intent of what the game should do on some situations.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request Changes

You have pseudocode but no actual code in your main.rb. For this milestone you are requested to put no logic but you need to work on interface in which user can play game without logic. You need to write code as requested by previous TSE. 

**Looking forward.
Best,
Arslan Bisharat
@arslanbisharat (slack)**

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request Changes 
I am sorry if you didn't get what I said in my previous review. You are requested to write actual code. But I can see you don't have any code but only comments. Please write the code. If something is unclear reach out to me on slack or schedule a 1:1 meeting with full-time TSEs. 

**Best,
Arslan Bisharat**

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] Like the first reviewer had already mentioned:

> In this step students are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`gets.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

> * [x] `[OPTIONAL]` game asks players for their names
> * [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
> * [x] `[REQUIRED]` game asks the player to select from available moves
> * [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
> * [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
> * [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
> * [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
> * [x] `[REQUIRED]` game repeats all actions for the next player's move

In this milestone you're building the game's user interface (what players will see). So fake(mock) the flow of the game. start by asking for their names, then display the board with instructions of how they should play. Fake (mimic) the back and forth gameplay between players by using a loop. 

It's not necessary to implement logic in this milestone, for example checking if a cell is already taken on the board or who a winner or loser is, etc. Just fake the flow of the game, show the board after each turn, and show where each player has played on the board.

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇
### Hi Team ✋🏽
Nicely done. Congratulations 🎉 on successfully completing another milestone. You were finally able to mock the behavior of the game using `puts` and `gets` methods. You have met all the minimum requirements for this project to be approved. It's a thumbs up for me. 👍🏽
You can go ahead and merge this PR.
Good luck on the upcoming milestones and Happy Coding 💻

**Pull request merged**
